language: node_js
node_js:
    - "8.9"

before_script:
    - npm install -g @angular/cli
    - cd src/app/client/
    - npm install
    - ng lint
    - cd ./../
    - npm install
script:
    - npm run test-with-coverage

