language: node_js
node_js:
    - "8.9"

before_script:
    - npm install -g @angular/cli
    - cd src/app/client/
    - npm install
    - ng lint
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd ./../'
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm install'
script:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run test-with-coverage || npm run test-coverage'

